#!/bin/ash

tail -f /tmp/filter-cookies.out

# mojo
#tshark -l -q -i "$IFACE" -f "dst port 80" -T fields -E separator=/s -e ip.src -e http.cookie | \
#grep --line-buffered -v "^192\.168\.123\.... $" | \
#awk -v urllength=`tput cols` -W interactive '{ print substr($0, 1, urllength+8) }'

