#!/bin/ash

tshark -i eth0 -l -f 'dst port 80' -n -T fields -e http.cookie | strings

# mojo
#tshark -l -q -i "$IFACE" -f "dst port 80" -T fields -E separator=/s -e ip.src -e http.cookie | \
#grep --line-buffered -v "^192\.168\.123\.... $" | \
#awk -v urllength=`tput cols` -W interactive '{ print substr($0, 1, urllength+8) }'

