#!/bin/ash

tail -f /tmp/filter-dns.out

# mojo
#tshark -l -q -i "$IFACE" -f "dst port 53 and dst host 192.168.123.1" -T fields -E separator=/s -e ip.src -e dns.qry.name | \
#awk -v urllength=`tput cols` -W interactive '{ print substr($0, 1, urllength+8) }'

