#!/bin/sh /etc/rc.common
# engine init

START=95

start() {

    # firewall allow all
    /usr/sbin/iptables -F
    /usr/sbin/iptables -P INPUT ACCEPT
    /usr/sbin/iptables -P OUTPUT ACCEPT
    /usr/sbin/iptables -P FORWARD ACCEPT

    # NAT
    /usr/sbin/iptables-A POSTROUTING -t nat -o eth2 -j MASQUERADE

    # kill dnsmasq
    /etc/init.d/dnsmasq stop
    chmod -x /etc/init.d/dnsmasq

    # start dhcpd
    /etc/init.d/dhcpd restart

}

